// Enriquecimiento verificado de Córdoba.
// Fuente primaria: fichas oficiales de la Agrupación de Hermandades y Cofradías de Córdoba
// (hermandadesdecordoba.es). Reseñas redactadas con palabras propias a partir de esas fichas.
const fs = require('fs');
const path = require('path');
const PAGES = JSON.parse(fs.readFileSync(path.join(__dirname, 'sources', 'cordoba-pages.json'), 'utf8'));
function pg(id) {
  const p = PAGES.find((x) => x.url.includes('/ver/' + id + '-'));
  if (!p) throw new Error('Página de Córdoba no encontrada: ' + id);
  return p;
}
const E = {};
function add(slug, id, o) {
  const p = pg(id);
  E[slug] = Object.assign({ url: p.url, web: p.web || '' }, o);
}

add('entrada-triunfal-cordoba', 4019, { no: 'Hermandad de la Entrada Triunfal de Jesús en Jerusalén (la Borriquita)', f: '1944 (primera estación en 1945; reorganizada en 1963)',
  t: [['Nuestro Padre Jesús de los Reyes', 'Juan Martínez Cerrillo'], ['Nuestra Señora de la Palma', 'Francisco Romero Zafra, 1991'], ['María Santísima de la Victoria', 'anónima s. XVIII']],
  h: 'Conocida como la Borriquita, tiene sus orígenes en 1944 con una cofradía creada en la iglesia de San Juan y Todos los Santos y realizó su primera estación de penitencia en 1945, con Rafael Sánchez Núñez como fundador. En 1963 se reorganizó con nuevos estatutos. Nuestro Padre Jesús de los Reyes es obra de Juan Martínez Cerrillo, que en 1963 hizo una nueva talla con un nuevo asno; Nuestra Señora de la Palma, de Francisco Romero Zafra (1991), se incorporó en 1993.' });
add('penas-de-santiago-cordoba', 4033, { no: 'Hermandad del Santísimo Cristo de las Penas', s: 'Iglesia de Santiago', f: '1955 (devoción desde el siglo XIII)',
  t: [['Santísimo Cristo de las Penas', 'anónima s. XIII'], ['Nuestra Señora Madre de los Desamparados', 'Antonio Eslava Rubio, 1973'], ['San Juan Evangelista', 'Antonio Eslava Rubio, 1978']],
  h: 'El Cristo de las Penas, de autor anónimo y probablemente del siglo XIII, es la imagen cristífera más antigua de la Semana Santa de Córdoba y se vincula a la cristianización de la ciudad por Fernando III en 1236. La hermandad actual se fundó en 1955 en la parroquia de Santiago, con primera estación de penitencia en 1957. En 1973 se incorporó como cotitular la Virgen de los Desamparados y en 1978 San Juan, ambas tallas de Antonio Eslava Rubio. Tras el incendio de la parroquia en 1979 regresó a Santiago en 1991.' });
add('vera-cruz-cordoba', 4087, { no: 'Hermandad de la Vera-Cruz', f: 'Devoción desde 1497; cofradía en el siglo XVI',
  t: [['Nuestro Señor de los Reyes', 'Antonio Dubé de Luque, 1987'], ['María Santísima del Dulce Nombre', 'Antonio Dubé de Luque, 1984']],
  h: 'La devoción a la Vera-Cruz en Córdoba se remonta a 1497, cuando se erigió una ermita en el Campo de San Antón; en el siglo XVI la cofradía se estableció en el convento de San Pedro el Real, con indulgencias del papa Paulo III en 1538. La hermandad actual tiene como primera titular la Cruz de Guía (2015) y rescata el Cristo de las Maravillas, un crucificado del siglo XVII atribuido al círculo de Martínez Montañés. Nuestro Señor de los Reyes, de Antonio Dubé de Luque, se bendijo en 1987 y la Virgen del Dulce Nombre, del mismo autor, en 1984.' });
add('el-rescatado-cordoba', 4040, { no: 'Hermandad de Nuestro Padre Jesús Nazareno Rescatado', s: 'Iglesia de Nuestra Señora de Gracia y San Eulogio (Padres Trinitarios)', f: 'Imagen de 1713',
  t: [['Nuestro Padre Jesús Nazareno Rescatado', 'Fernando Díaz de Pacheco, 1713'], ['María Santísima de la Amargura', 'José Callejón y Rafael Díaz Peno, 1942']],
  h: 'La hermandad nace de la devoción a Nuestro Padre Jesús Nazareno Rescatado, conocido como el Señor de Córdoba, tallado en 1713 por el granadino Fernando Díaz de Pacheco a imagen de Jesús de Medinaceli de Madrid. Se venera en la parroquia de los Padres Trinitarios, con especial devoción los viernes y, sobre todo, el primer viernes de marzo. Lleva el escapulario trinitario en el pecho, símbolo de su rescate por la Orden Trinitaria. La imagen se restauró en 1991 y en 2021.' });
add('la-esperanza-cordoba', 4036, { no: 'Hermandad de la Esperanza', s: 'Parroquia de San Andrés Apóstol', f: '1939',
  t: [['Nuestro Padre Jesús de las Penas', 'Juan Martínez Cerrillo'], ['María Santísima de la Esperanza', 'Juan Martínez Cerrillo, 1947']],
  h: 'Se fundó en 1939 por un grupo de cofrades encabezado por Rafael Sánchez Núñez; el 8 de diciembre de ese año se aprobaron sus primeros estatutos y quedó establecida en la parroquia de Santa Marina de Aguas Santas. Su Nazareno, obra del cordobés Juan Martínez Cerrillo y conocido popularmente como «el Gitano», es una de las imágenes más veneradas de la Semana Santa de Córdoba; los esclavos, romanos y el sanedrita del paso son de Antonio Bernal Redondo. La Virgen, también de Cerrillo (1947), se restauró en 2011.' });
add('el-amor-cordoba', 4039, { no: 'Hermandad del Santísimo Cristo del Amor', s: 'Parroquia de Jesús Divino Obrero', f: 'Cristo del siglo XVI; hermandad actual de finales del siglo XX',
  t: [['Nuestro Padre Jesús del Silencio en el desprecio de Herodes', 'Luis Ortega Bru, 1980'], ['Santísimo Cristo del Amor', 'atrib. Martín de la Torre, h. 1553']],
  h: 'La hermandad tiene sus raíces en un pequeño Crucificado venerado desde el siglo XVI en la ermita de San José, junto a la plaza de la Magdalena, y rescatado para el culto en 1954 por el obispo fray Albino, que le dio la advocación del Amor. Desde 1991 recibe culto en la iglesia de Jesús Divino Obrero junto a Nuestro Padre Jesús del Silencio en el desprecio de Herodes, la única obra de Luis Ortega Bru en Córdoba, donada por un grupo de devotos gaditanos. Su primera estación de penitencia fue el Domingo de Ramos de 1992.' });
add('el-huerto-cordoba', 4034, { no: 'Hermandad del Huerto', f: 'Raíces en los siglos XVI-XVII; consolidada en 1720',
  t: [['Nuestro Padre Jesús de la Oración en el Huerto', 'anónima s. XVII (círculo de Pedro de Mena)'], ['Jesús Amarrado a la Columna', 'anónima s. XVII'], ['María Santísima de la Candelaria', 'Antonio Rubio, 1974']],
  h: 'Sus raíces están en las cofradías penitenciales de los siglos XVI y XVII: en 1607 ya se documentan gastos de la Cofradía de la Oración en el Huerto y Nuestra Señora de Loreto, en San Nicolás de la Axerquía, y en 1720 se consolidó la hermandad. El Señor de la Oración en el Huerto es una talla anónima del siglo XVII atribuida al círculo de Pedro de Mena; acompañan al paso un ángel de José Antonio Navarro Arteaga (2004) y los apóstoles durmientes de Jesús Gálvez (2018). La Virgen de la Candelaria es de Antonio Rubio (1974).' });
add('la-merced-cordoba', 4041, { no: 'Venerable, Ilustre y Mercedaria Hermandad del Santísimo Sacramento y Cofradía de Nazarenos de Nuestro Padre Jesús Humilde en la Coronación de Espinas, Nuestra Madre y Señora Santa María de la Merced y San Antonio de Padua', s: 'Iglesia de San Antonio de Padua (Parroquia del Buen Pastor)', f: '1954',
  t: [['Nuestro Padre Jesús Humilde en su Coronación de Espinas', 'Francisco Buiza, 1978'], ['Nuestra Madre y Señora Santa María de la Merced', '1976 (manos de Francisco Buiza)']],
  h: 'Fundada en 1954 bajo el amparo de la parroquia del Buen Pastor y San Antonio de Padua. Su Cristo de la Coronación de Espinas, de Francisco Buiza (1978), va acompañado de dos romanos y un sayón de Francisco Pinto Berraquero (1984-1985); la Virgen de la Merced, tallada en 1976, sustituyó a una antigua dolorosa deteriorada; Buiza le hizo nuevas manos poco antes de morir y en 2022 la restauró Ana Infante de la Torre.' });
add('la-estrella-cordoba', 4085, { no: 'Hermandad Sacramental del Dulce Nombre de Jesús y Cofradía de Nazarenos del Santísimo Ecce-Homo, Nuestro Padre Jesús de la Redención ante Caifás, Negaciones y Lágrimas de San Pedro y Nuestra Señora de la Estrella', s: 'Parroquia de San Fernando', f: '1981',
  t: [['Nuestro Padre Jesús de la Redención', 'Miguel Ángel González Jurado, 1992'], ['Nuestra Señora de la Estrella', 'Juan Ventura, 1986']],
  h: 'Inició su andadura en 1981 con primera sede en la parroquia de San Juan y Todos los Santos (Trinidad). Nuestro Padre Jesús de la Redención, obra del cordobés Miguel Ángel González Jurado (1992), representa a Jesús maniatado ante Caifás y se bendijo el 5 de abril de 1992 en San Fernando. La Virgen de la Estrella, del sevillano Juan Ventura (1986), se bendijo el 16 de noviembre de 1986 en la capilla de San Juan de los Caballeros.' });
add('animas-cordoba', 4096, { no: 'Hermandad del Santísimo Cristo de los Remedios y Benditas Ánimas del Purgatorio', s: 'Iglesia de San Lorenzo', f: 'Raíces a finales del siglo XV',
  t: [['Santísimo Cristo del Remedio de Ánimas', 'anónima s. XVI (escuela genovesa)'], ['Nuestra Señora Madre de Dios en sus Tristezas', 'atrib. Antonio del Castillo, s. XVII']],
  h: 'Tiene sus raíces en las antiguas cofradías de Ánimas que existían en Córdoba desde finales del siglo XV. El Cristo del Remedio de Ánimas, una de las imágenes más queridas de la ciudad, es una talla anónima del siglo XVI atribuida a la escuela genovesa, que representa a Cristo sorprendido por la muerte; se restauró en 1950 y en 2014. La Virgen de las Tristezas se atribuye al imaginero Antonio del Castillo (siglo XVII).' });
add('la-sentencia-cordoba', 4091, { no: 'Hermandad de la Sentencia', s: 'Parroquia de San Nicolás de la Villa', f: '1945',
  t: [['Nuestro Padre Jesús de la Sentencia', 'Juan Martínez Cerrillo, 1944'], ['María Santísima de Gracia y Amparo', 'anónima']],
  h: 'Llenó el vacío del Lunes Santo en Córdoba al fundarse en 1945, por iniciativa de feligreses de San Nicolás de la Villa liderados por el párroco Paulino Seco de Herrera y con el apoyo del obispo fray Albino. El Señor, obra de Juan Martínez Cerrillo, se encargó en 1944, se bendijo en diciembre de ese año y salió por primera vez en 1945; representa la condena de Jesús por Pilato ante el Sanedrín y la liberación de Barrabás.' });
add('via-crucis-cordoba', 4092, { no: 'Hermandad del Santo Cristo de la Salud', s: 'Parroquia de San Juan y Todos los Santos (Trinidad)', f: '1972 (devoción desde el siglo XV)',
  t: [['Santo Cristo de la Salud', 'anónima h. 1590']],
  h: 'La devoción al Cristo de la Salud se remonta al siglo XV y la hermandad actual se fundó en 1972 en San Juan y Todos los Santos. La talla, anónima, data de hacia 1590 según un documento hallado en su interior durante la restauración de Miguel Arjona en 1974. Como indica su nombre, procesiona en Vía Crucis y sin paso: tres hermanos elegidos por sorteo portan el Cristo a hombros.' });
add('presentacion-al-pueblo-cordoba', 4125, { no: 'Hermandad de Nuestro Padre Jesús de los Afligidos (Presentación al Pueblo)', s: 'Iglesia Parroquial de San Vicente Ferrer', f: '2006', dia: 'Hermandades agrupadas',
  t: [['Nuestro Padre Jesús de los Afligidos', 'Manuel Martín Nieto, 2016']],
  h: 'Nació en 2006 por iniciativa de un grupo de vecinos del barrio de Cañero, con el apoyo del párroco Manuel Vida Ruiz, en la parroquia de San Vicente Ferrer. Su titular es Nuestro Padre Jesús de los Afligidos, talla en cedro de 1,85 metros del sevillano Manuel Martín Nieto, que representa la presentación de Jesús al pueblo (Ecce Homo) y se bendijo en 2016. El paso de misterio sigue en proceso: en 2022 se estrenaron Pilatos y un soldado romano.' });
add('la-universitaria-cordoba', 4097, { no: 'Hermandad Universitaria', s: 'Iglesia de San Pedro de Alcántara', f: '1989',
  t: [['Santo Cristo de la Universidad', 'Juan Manuel Miñarro, 2010'], ['Nuestra Señora de la Presentación', 'Miguel Ángel González Jurado, 1990']],
  h: 'Fundada el 19 de diciembre de 1989, se estableció en la iglesia de San Pedro de Alcántara, junto a la Facultad de Filosofía y Letras, y en 2006 obtuvo el título de hermandad de penitencia. El Santo Cristo de la Universidad, de Juan Manuel Miñarro, se bendijo el 13 de marzo de 2010 y salió en 2011; Nuestra Señora de la Presentación, de González Jurado, se bendijo el 9 de junio de 1990.' });
add('la-agonia-cordoba', 4098, { no: 'Hermandad de la Agonía', f: 'Finales de los años setenta (estatutos reconocidos en 1988)',
  t: [['Santísimo Cristo de la Agonía', 'Antonio Castillo Ariza, 1954'], ['Santísima Virgen de la Salud', 'Miguel Ángel González Jurado, 1988']],
  h: 'Surgió a finales de los años setenta por iniciativa de vecinos del barrio del Naranjo; sus primeros estatutos se aprobaron de forma provisional el 7 de abril de 1979 y no fueron reconocidos oficialmente hasta 1988. El Cristo de la Agonía es una talla de 1954 de Antonio Castillo Ariza, restaurada en 1992 por Miguel Arjona Navarro; la Virgen de la Salud, de González Jurado (1988), fue remodelada por el mismo autor en 2006.' });
add('la-sangre-cordoba', 4099, { no: 'Hermandad de la Sangre', s: 'Monasterio Cisterciense de la Inmaculada Concepción', f: '1974',
  t: [['Nuestro Padre Jesús de la Sangre', 'Antonio Eslava Rubio, 1978'], ['Santísimo Cristo de la Conversión', 'Antonio Bernal, 2009']],
  h: 'En mayo de 1974 un grupo de jóvenes cordobeses decidió sacar en procesión una cruz por el barrio de Capuchinos, germen de la cofradía. Nuestro Padre Jesús de la Sangre es obra de Antonio Eslava (1978) y representa el desprecio del pueblo; el misterio incluye siete figuras de Francisco Pinto Berraquero (1988) y un trono coronado por la Loba capitolina. El Cristo de la Conversión, pequeña talla de Antonio Bernal (2009), encabeza el paso de palio de Nuestra Señora Reina de los Ángeles.' });
add('el-buen-suceso-cordoba', 4100, { no: 'Hermandad del Señor del Buen Suceso y Nuestra Señora de los Dolores', s: 'Iglesia de San Andrés', f: '1973',
  t: [['Nuestro Padre Jesús del Buen Suceso', 'anónima finales s. XVII o principios s. XVIII'], ['Nuestra Señora de los Dolores', 'anónima (restaurada por Miguel Ángel González Jurado, 2003)'], ['María Santísima de la Caridad', 'Miguel Ángel González Jurado, 1991']],
  h: 'El 2 de octubre de 1973 se aprobaron las reglas de la cofradía, impulsada por antiguos alumnos del Colegio Parroquial de San Andrés. La imagen del Señor, originalmente de la extinta Cofradía del Santo Crucifijo, es una talla anónima de finales del siglo XVII o principios del XVIII que Antonio Bernal y Francisco Romero adaptaron a la iconografía de Nazareno en 1988. González Jurado hizo las figuras del misterio (2003-2006) y la Virgen de la Caridad (1991).' });
add('la-santa-faz-cordoba', 4101, { no: 'Hermandad de Penitencia de la Santa Faz de Nuestro Señor Jesucristo y María Santísima del Perdón', s: 'Parroquia de San Juan y Todos los Santos (Trinidad)', f: '1982',
  t: [['Nuestro Padre Jesús Nazareno de la Santa Faz', 'Antonio Dubé de Luque, 1988'], ['María Santísima de la Trinidad', 'Antonio Salto Román, 1989']],
  h: 'En marzo de 1982 un grupo de jóvenes cofrades fundó la hermandad, que tras intentar establecerse en la parroquia de Cristo Rey encontró acogida en la de la Trinidad. El Nazareno de la Santa Faz, que representa el encuentro con la Verónica, es de Antonio Dubé de Luque (1988) y la Virgen de la Trinidad, de Antonio Salto Román (1989).' });
add('el-prendimiento-cordoba', 4102, { no: 'Hermandad Salesiana y Cofradía de Nazarenos de Nuestro Padre Jesús, Divino Salvador, en su Prendimiento, Nuestra Señora de la Piedad y San Juan Bosco', s: 'Santuario de María Auxiliadora', f: '1952',
  t: [['Nuestro Padre Jesús, Divino Salvador, en su Prendimiento', 'Antonio Dubé de Luque, 1990'], ['Nuestra Señora de la Piedad', 'Juan Martínez Cerrillo, 1957'], ['San Juan Bosco', 'Edwin González Solís, 2016']],
  h: 'Fundada el 7 de octubre de 1952 por antiguos alumnos del Colegio Salesiano de Córdoba. Su Señor del Prendimiento es de Antonio Dubé de Luque (1990) y guarda en su interior restos de la primitiva talla de Antonio Castillo Ariza (1952); el paso de misterio, con los apóstoles, soldados y Judas, es obra de Antonio Bernal (1998-2008). La Virgen de la Piedad es de Juan Martínez Cerrillo (1957-1958).' });
add('el-perdon-cordoba', 4104, { no: 'Hermandad del Perdón', s: 'Iglesia de San Roque - Buen Pastor', f: '1990',
  t: [['Nuestro Padre Jesús del Perdón', 'Francisco Romero Zafra, 1993'], ['María Santísima del Rocío y Lágrimas', 'Francisco Romero Zafra, 1990']],
  h: 'Se fundó en 1990 en la parroquia de San Miguel Arcángel en torno a una dolorosa de Francisco Romero Zafra. Nuestro Padre Jesús del Perdón, del mismo escultor y entregado a la hermandad en 1993, representa el desprecio de Herodes; las figuras secundarias del misterio son de Manuel Luque Bonillo (1998-2000). La Virgen del Rocío y Lágrimas se bendijo el Sábado Santo de 1990.' });
add('el-calvario-cordoba', 4105, { no: 'Hermandad de la Sagrada Pasión y Vía Sacra de Nuestro Señor Jesucristo (Calvario)', s: 'Real Parroquia de San Lorenzo Mártir', f: '1722',
  t: [['Nuestro Padre Jesús del Calvario', 'Fray Juan de la Concepción, 1724']],
  h: 'Fundada el 20 de julio de 1722 en la parroquia de San Lorenzo Mártir para meditar sobre la Pasión de Cristo a través del Vía Crucis, práctica impulsada por el beato Álvaro de Córdoba. Su titular, Nuestro Padre Jesús del Calvario, fue tallado en 1724 por el trinitario fray Juan de la Concepción, y su bendición el 9 de abril de 1724 marcó el inicio de su culto en el barrio de San Lorenzo. Se restauró en 1949, 1984 y 2001.' });
add('la-paz-cordoba', 4106, { no: 'Hermandad de la Paz y Esperanza', s: 'Iglesia conventual del Santo Ángel (Capuchinos)', f: '1939',
  t: [['Nuestro Padre Jesús de la Humildad y Paciencia', 'Juan Martínez Cerrillo, 1943'], ['María Santísima de la Paz y Esperanza', 'Juan Martínez Cerrillo, 1939']],
  h: 'Fundada en 1939 en el barrio de San Lorenzo por jóvenes cofrades, muchos de ellos excombatientes, en torno al Señor de la Humildad y Paciencia. Su misterio actual, de Antonio Bernal Redondo (1997), es uno de los de mayores dimensiones de la Semana Santa cordobesa y lo portan 50 costaleros. La Virgen de la Paz y Esperanza, la «Reina de Capuchinos», es de Juan Martínez Cerrillo (1939), la primera talla que el imaginero hizo para Córdoba.' });
add('la-misericordia-cordoba', 4107, { no: 'Hermandad del Santísimo Cristo de la Misericordia y Nuestra Señora de las Lágrimas', s: 'Basílica Menor de San Pedro', f: 'Hermandades de 1534 y 1673 fusionadas en 1741; refundada en 1937',
  t: [['Santísimo Cristo de la Misericordia', 'anónima s. XVI'], ['Nuestra Señora de las Lágrimas en su Desamparo', 'anónima finales s. XVI']],
  h: 'Tiene sus raíces en dos antiguas cofradías: la del Santísimo Sacramento (1534) y la de los Santos Mártires (1673), fusionadas en 1741; en 1937 un grupo de jóvenes la refundó. Venera las reliquias de los Santos Mártires de Córdoba, halladas en 1575 y guardadas en una urna de plata del siglo XVIII en la basílica de San Pedro. El Cristo de la Misericordia es una talla anónima del siglo XVI restaurada en 1939 y en 1983.' });
add('la-pasion-cordoba', 4149, { no: 'Hermandad de Nuestro Padre Jesús de la Pasión, María Santísima del Amor y San Juan Evangelista', s: 'Iglesia de Nuestra Señora de la Paz', f: 'Orígenes en el siglo XVII; fundada oficialmente en 1939',
  t: [['Nuestro Padre Jesús de la Pasión', 'anónima s. XVII (escuela sevillana)'], ['María Santísima del Amor', 'anónima s. XVII-XVIII']],
  h: 'Sus orígenes se remontan al siglo XVII, vinculados al antiguo monasterio de San Basilio y al barrio del Alcázar Viejo; se fundó oficialmente en 1939. Nuestro Padre Jesús de la Pasión es una talla del siglo XVII atribuida a la escuela sevillana que recuperó su policromía en 2002 gracias a Antonio Bernal; originalmente bendecía las huertas con un brazo articulado. La Virgen del Amor, dolorosa de candelero del XVII o XVIII, fue restaurada por Juan Martínez Cerrillo en 1946 y por Antonio Bernal en 2001.' });
add('la-piedad-cordoba', 4103, { no: 'Hermandad del Santísimo Cristo de la Piedad y Nuestra Señora de la Esperanza', s: 'Iglesia de San Antonio María Claret (Las Palmeras)', f: '1972',
  t: [['Santísimo Cristo de la Piedad', 'Antonio Bernal, 2023'], ['María Santísima de Vida, Dulzura y Esperanza Nuestra', 'Francisco Pascual Reyes, 1945 (transformada por Juan Ventura)']],
  h: 'Fundada el 21 de marzo de 1972 en la parroquia de San Antonio María Claret, en el barrio de Las Palmeras, para fomentar la formación religiosa y apoyar a la comunidad. El Cristo de la Piedad actual es de Antonio Bernal (2023) y sustituye a un crucificado anónimo del siglo XVIII; la Virgen fue tallada originalmente como ángel por Francisco Pascual Reyes en 1945 y transformada en dolorosa por Juan Ventura; los claretianos de Sevilla la donaron en 1983.' });
add('jesus-nazareno-cordoba', 4108, { no: 'Cofradía de Nuestro Padre Jesús Nazareno', s: 'Iglesia Hospital de Jesús Nazareno', f: 'Primera mención documental en 1487',
  t: [['Nuestro Padre Jesús Nazareno', 'anónima finales s. XVI o principios s. XVII'], ['María Santísima Nazarena', 'anónima s. XVII']],
  h: 'Es una de las hermandades más antiguas de Córdoba, con raíces en el siglo XV: en 1487 aparece documentada una cofradía asistencial con hospital en el barrio de Santiago. En el XVII vivió su mayor esplendor y en 1975 incorporó a María Santísima Nazarena; en el siglo XXI pasó a la tarde del Jueves Santo, abriendo la jornada. El Nazareno es una talla anónima de álamo blanco del XVI-XVII, restaurada en 1978.' });
add('la-caridad-cordoba', 4112, { no: 'Hermandad de la Santa Caridad', s: 'Parroquia de San Francisco y San Eulogio', f: 'Orígenes en el siglo XV',
  t: [['Señor de la Caridad', 'anónima finales s. XVI o principios s. XVII']],
  h: 'Una de las más antiguas de Córdoba, con orígenes en el siglo XV y su labor hospitalaria y caritativa apoyada por reyes como Enrique IV. El Cristo de la Caridad, de finales del XVI o principios del XVII, perteneció al Hospital de la Caridad y fue donado a la cofradía en 1614 por Juan Draper, que lo recibió como pago de una deuda; es una talla manierista de tamaño mayor que el natural, restaurada por última vez en 2017.' });
add('jesus-caido-cordoba', 4111, { no: 'Hermandad de Nuestro Padre Jesús Caído', f: '1676 (donación de la imagen); primera procesión en 1779',
  t: [['Nuestro Padre Jesús Caído', 'anónima mediados s. XVII'], ['Nuestra Señora del Mayor Dolor en su Soledad', 'anónima primer tercio s. XVIII']],
  h: 'La devoción a Jesús Caído en Córdoba se remonta a 1676, cuando el canónigo Francisco Bañuelos y Murillo donó una imagen de Jesús Nazareno caído bajo la cruz al convento de San José (Carmelitas Descalzos). La cofradía hizo su primera procesión el Jueves Santo de 1779 y tras su reorganización en 1851 recuperó su esplendor. La imagen, anónima de mediados del XVII, se restauró en 1979 y 2017; la Virgen del Mayor Dolor en su Soledad procesiona bajo un palio de grandes dimensiones.' });
add('la-cena-cordoba', 4109, { no: 'Hermandad de la Sagrada Cena', s: 'Parroquia Beato Álvaro de Córdoba', f: '1983',
  t: [['Nuestro Padre Jesús de la Fe', 'Miguel Ángel González Jurado, 1993'], ['María Santísima de la Esperanza del Valle', 'Miguel Ángel González Jurado, 2001'], ['Santísimo Cristo de la Luz', '2008']],
  h: 'Tiene raíces en las hermandades del Santísimo Sacramento de 1630 y 1631, fusionadas en 1799. La hermandad actual nació en 1983 en la tertulia cofrade «El Llamador», vinculada a la parroquia de la Trinidad, y realizó su primera estación de penitencia el Jueves Santo de 1994. Su misterio de la Cena es de González Jurado (1993), que también talló la Virgen de la Esperanza del Valle (2001).' });
add('las-angustias-cordoba', 4114, { no: 'Hermandad de Nuestra Señora de las Angustias', s: 'Iglesia de San Agustín', f: '1558',
  t: [['Nuestra Señora de las Angustias', 'Juan de Mesa, 1627']],
  h: 'Una de las cofradías más antiguas de Córdoba, fundada en 1558 en el convento de San Agustín. Su grupo escultórico de la Virgen de las Angustias sosteniendo el cuerpo de Cristo es la obra cumbre del cordobés Juan de Mesa, considerada su última creación (1627) y llegada a Córdoba en 1628; la Virgen, de talla completa, tiene cinco lágrimas, símbolo de la quinta angustia, y sostiene una espina con la mano derecha. Procesiona cada Jueves Santo.' });
add('cristo-de-gracia-el-esparraguero-cordoba', 4113, { no: 'Hermandad del Cristo de Gracia', f: 'Imagen donada en 1607',
  t: [['Santísimo Cristo de Gracia', 'anónima finales s. XVI o principios s. XVII']],
  h: 'Sus orígenes están documentados en un breve manuscrito, el Protocolo, único vestigio de su historia. El Cristo de Gracia fue donado en 1607 por Francisca de la Cruz al convento de la orden trinitaria; es una talla anónima de finales del XVI o principios del XVII elaborada con la técnica mexicana de médula de caña de maíz, fibras y telas encoladas, propia de los «cristos tarascos».' });
add('la-buena-muerte-cordoba', 4115, { no: 'Hermandad de la Buena Muerte', s: 'Real Colegiata de San Hipólito', f: '1943',
  t: [['Santísimo Cristo de la Buena Muerte', 'Antonio Castillo Lastrucci, 1945'], ['Nuestra Señora Reina de los Mártires', 'Antonio Castillo Lastrucci, 1945']],
  h: 'Fundada en 1943 por un grupo de jóvenes profesionales, médicos y abogados sobre todo, para enriquecer la Semana Santa de Córdoba. Hizo su primera estación de penitencia en la madrugada del Viernes Santo de 1946 y fue la única cofradía que procesionaba en esa jornada. Su Cristo, de Antonio Castillo Lastrucci (1945), se inspira en el de la Buena Muerte de los Estudiantes de Sevilla, de Juan de Mesa.' });
add('la-soledad-cordoba', 4117, { no: 'Hermandad de la Soledad', s: 'Iglesia de Santa María de Guadalupe', f: '1975',
  t: [['María Santísima en su Soledad', 'Luis Álvarez Duarte, 1975']],
  h: 'Fundada en 1975 en la iglesia de San Miguel con la idea de incorporar el sello franciscano a la Semana Santa de Córdoba. Su Virgen, de Luis Álvarez Duarte (1975), rompe con el esquema tradicional: una mujer madura de facciones marcadas, con los ojos enrojecidos y dos lágrimas. Tras el incendio de Santiago en 1980 el propio autor la restauró y mantuvo una policromía más oscura. Procesiona sola, con la corona de espinas en las manos, seguida de una cruz vacía.' });
add('la-expiracion-cordoba', 4118, { no: 'Hermandad del Santísimo Cristo de la Expiración', s: 'Real Iglesia de San Pablo', f: 'Raíces en el siglo XVII',
  t: [['Santísimo Cristo de la Expiración', 'anónima último cuarto s. XVII (atribuida a la escuela granadina)'], ['María Santísima del Silencio', 'anónima s. XVIII']],
  h: 'Con raíces en el siglo XVII, nació en el convento de San Pedro el Real bajo la advocación de San Diego y San Acacio. El Cristo de la Expiración, de autor desconocido y atribuido a la escuela granadina, posiblemente al círculo de Pedro de Mena, pasó a San Pablo en 1904 y recuperó su culto cofrade en 1918; se restauró por última vez en 1985. La Virgen del Silencio, dolorosa del siglo XVIII, se incorporó en 1919.' });
add('el-descendimiento-cordoba', 4119, { no: 'Hermandad del Descendimiento', s: 'Parroquia de San José y Espíritu Santo', f: '1908',
  t: [['Santísimo Cristo del Descendimiento', 'Amadeo Ruiz Olmos, 1938'], ['María Santísima del Refugio', 'Miguel Ángel González Jurado, 1993'], ['Santos Varones', 'Alfonso Castellano, 2010']],
  h: 'Sus antecedentes se remontan a una cofradía penitencial del siglo XVI que desapareció pronto; la hermandad actual se fundó en 1908. El Cristo del Descendimiento es del valenciano Amadeo Ruiz Olmos (1938), restaurado en 1992 por González Jurado, que también hizo la Virgen del Refugio y San Juan (1993) y las tres Marías (1997-1999); los Santos Varones son de Alfonso Castellano (2010).' });
add('los-dolores-cordoba', 4120, { no: 'Hermandad de Nuestra Señora de los Dolores', s: 'Iglesia-Hospital de San Jacinto', f: 'Congregación servita del siglo XVIII',
  t: [['Santísimo Cristo de la Clemencia', 'Amadeo Ruiz Olmos, 1938'], ['Nuestra Señora de los Dolores', 'Juan Prieto, 1719']],
  h: 'Tiene sus raíces en el siglo XVIII, con la Congregación de Nuestra Señora de los Dolores como Tercera Orden Servita. Su Virgen fue encargada en 1717 al cordobés Juan Prieto, que tras un primer intento fallido entregó la talla actual en 1719. El Cristo de la Clemencia, donado en 1939, es obra del valenciano Amadeo Ruiz Olmos (1938); procesionó por primera vez en 1949 y fue restaurado en 1984 por Miguel Arjona.' });
add('santo-sepulcro-cordoba', 4121, { no: 'Cofradía del Santo Sepulcro', s: 'Iglesia del Colegio de Santa Catalina', f: 'Último tercio del siglo XVI (reglas de 1573)',
  t: [['Nuestro Señor Jesucristo del Santo Sepulcro', 'anónima principios s. XVII']],
  h: 'Tiene sus orígenes en el último tercio del siglo XVI, vinculada a los carmelitas calzados; sus primeras reglas se aprobaron el 5 de marzo de 1573, aunque ya existía antes. La imagen, una talla anónima de principios del XVII que fue un crucificado de brazos articulados adaptado para representar a Cristo yacente, procesiona en una urna de palosanto de Rafael Juliá Villaplana (siglo XIX).' });
add('la-conversion-cordoba', 4122, { no: 'Hermandad de la Conversión del Buen Ladrón', f: 'Taller cofrade de 2003; hermandad posterior',
  t: [['Santísimo Cristo de la Oración y la Caridad', 'Pedro García Velasco, 2016']],
  h: 'Tiene sus raíces en el taller cofrade «Nuestra Señora del Rosario», creado en 2003 por niños del colegio de Mirasierra bajo la guía de Rafael Dorado Gutiérrez. Su Cristo, de Pedro García Velasco (2016), representa la conversión del Buen Ladrón; gira el rostro a la izquierda como homenaje al crucificado de Juan de Ávalos al que la hermandad rendía culto antes. La Virgen de la Salud y el Consuelo es una dolorosa del siglo XVIII.' });
add('el-resucitado-cordoba', 4123, { no: 'Hermandad de Jesús Resucitado y Benditas Ánimas', s: 'Iglesia de Santa Marina de Aguas Santas', f: 'Raíces en el siglo XVI',
  t: [['Nuestro Señor Resucitado', 'Juan Manuel Miñarro, 1988']],
  h: 'Una de las cofradías más antiguas de Córdoba, con raíces del siglo XVI en la parroquia de Santa Marina, donde se dedicaba al culto de las Ánimas del Purgatorio. La imagen del Resucitado es de Juan Manuel Miñarro, tallada en tilo, se bendijo el 15 de mayo de 1988 y procesionó por primera vez en 1989; mide 1,87 metros y bendice con la mano derecha. Sale cada Domingo de Resurrección.' });

// Hermandades agrupadas que no figuraban en el listado anterior.
E['lagrimas-cordoba'] = Object.assign({ url: pg(4124).url, web: '', n: 'Lágrimas', dia: 'Hermandades agrupadas', no: 'Hermandad del Santísimo Cristo de las Lágrimas y María Santísima de las Penas', s: 'Iglesia de Nuestra Señora de la Asunción (Parque Figueroa)', f: '1999',
  t: [['Santísimo Cristo de las Lágrimas', 'Miguel Arjona Navarro, 1999']],
  h: 'Nació en 1999 entre devotos de la iglesia de Nuestra Señora de la Asunción, en el barrio del Parque Figueroa, en torno a la imagen del Santísimo Cristo de las Lágrimas. Es una talla moderna de Miguel Arjona Navarro que representa a Cristo crucificado aún con vida, con los ojos abiertos y sin la herida del costado, una iconografía única en Córdoba. Prepara un paso de misterio con la escena de la Exaltación, aprobado en 2017.' });
E['dolores-de-alcolea-cordoba'] = Object.assign({ url: pg(4233).url, web: 'https://doloresalcolea.es', n: 'Dolores de Alcolea', dia: 'Hermandades agrupadas', no: 'Hermandad de los Dolores de Alcolea', s: 'Parroquia de Nuestra Señora de los Ángeles (Alcolea)', f: '1981',
  t: [['María Santísima de los Dolores', 'Francisco Buiza, 1981']],
  h: 'Fundada en 1981 por un grupo de jóvenes cristianos con el apoyo de los párrocos locales, para cubrir la ausencia de una cofradía penitencial en esta barriada situada a 10 km de Córdoba. Su Virgen de los Dolores, de Francisco Buiza (otoño de 1981), es considerada su última obra mariana y se bendijo el 20 de diciembre de ese año. Cuenta con unos 450 hermanos y mantiene procesiones el Jueves y el Viernes Santo.' });

module.exports = E;
