// Enriquecimiento verificado de Jaén.
// Fuente primaria: fichas oficiales de la Agrupación de Cofradías y Hermandades de la Ciudad de Jaén (cofradiasjaen.org).
const B = 'https://cofradiasjaen.org/';
const E = {};
function add(slug, off, o) { E[slug] = Object.assign({ url: B + off + '/' }, o); }

add('la-borriquilla-jaen', 'borriquilla', { no: 'Real, Ilustre y Fervorosa Hermandad Franciscana y Cofradía de Nazarenos de Nuestro Padre Jesús de la Salud entrando en Jerusalén, María Santísima de la Paz, San Pedro, San Juan y Santiago Apóstoles', s: 'Parroquia de Nuestra Señora de Belén y San Roque', f: '1946', web: 'http://www.hermandadsaludypaz.org',
  t: [['Nuestro Padre Jesús de la Salud entrando en Jerusalén', 'Antonio Dubé de Luque, 2002'], ['María Santísima de la Paz', 'Antonio Dubé de Luque, 1991']],
  h: 'Fundada en 1946, abre la Semana Santa de Jaén con la «llamá» a la puerta del templo. En 1961 se bendijo una imagen del Señor de Jacinto Higueras Cátedra, y en 1964 la cofradía se reorganizó a fondo. En 1991 incorporó a María Santísima de la Paz, de Antonio Dubé de Luque, bendecida en enero de 1992; el mismo autor talló en 2002 la imagen actual del Señor.' });
add('santa-cena-jaen', 'santa-cena', { no: 'Hermandad Sacramental de Jesús Salvador en Santa Cena y María Santísima de la Caridad y Consolación', s: 'Iglesia parroquial de San Juan Pablo II', f: '1998', web: 'http://www.santacenajaen.org',
  t: [['Jesús Salvador en su Santa Cena', 'Antonio Bernal Redondo, 2000'], ['María Santísima de la Caridad y Consolación', 'Antonio Bernal Redondo, 1999']],
  h: 'Nació el 27 de agosto de 1998, cuando un grupo de cristianos se reunió para fundar una hermandad penitencial. Sus dos titulares son del cordobés Antonio Bernal Redondo: la Virgen de la Caridad y Consolación (1999) y Jesús Salvador en su Santa Cena (2000).' });
add('la-estrella-jaen', 'piedad-y-estrella', { no: 'Hermandad Dominica y Cofradía de Nazarenos de Nuestro Padre Jesús de la Piedad, en su Sagrada Presentación al Pueblo, María Santísima de la Estrella, Nuestra Señora del Rosario y Santo Domingo de Guzmán', s: 'Parroquia de Nuestra Señora de la Merced', f: '1955 (refundada en 1982)', web: 'http://www.piedadyestrella.es',
  t: [['Nuestro Padre Jesús de la Piedad', 'anónima s. XVII'], ['María Santísima de la Estrella', 'Domingo Sánchez-Mesa, 1956']],
  h: 'Fundada en 1955, encargó en Granada a Domingo Sánchez Mesa la imagen de la Virgen de la Estrella (1956). Tras un periodo de inactividad se refundó en 1982. Su Señor de la Piedad, en su Presentación al Pueblo, es una talla anónima del siglo XVII.' });
add('el-huerto-vera-cruz-jaen', 'oracion-en-el-huerto', { no: 'Primitiva, Pontificia y Real Congregación del Santísimo Cristo de la Vera Cruz y María Santísima de los Dolores (sección del Domingo de Ramos)', s: 'Basílica Menor de San Ildefonso', f: '1541', web: 'http://www.veracruzjaen.es',
  t: [['Jesús orando en el Huerto', 'grupo valenciano de 1918 (nueva cabeza de Juan Abascal, 1971)'], ['María Santísima de los Desamparados', 'Ventura Gómez Rodríguez, 2007']],
  h: 'Es la salida del Domingo de Ramos de la Congregación de la Vera Cruz, la primera cofradía penitencial fundada en Jaén (1541). El grupo de la Oración en el Huerto se hizo en Valencia en 1918, inspirado en la obra de Salzillo para Murcia, y en 1971 Juan Abascal le talló una nueva cabeza. La Virgen de los Desamparados es del sevillano Ventura Gómez Rodríguez (2006-2007).' });
add('caridad-y-salud-jaen', 'caridad-y-salud', { no: 'Hermandad de Jesús de la Caridad ante Caifás, María Santísima de la Salud y San Eufrasio', s: 'Parroquia Santa María Madre de la Iglesia', f: '2012', web: 'http://www.caridadysalud.com',
  t: [['Jesús de la Caridad ante Caifás', ''], ['María Santísima de la Salud', 'Antonio Bernal Redondo, 2011']] });
add('la-amargura-jaen', 'amargura', { no: 'Hermandad del Santo Rosario y Cofradía de Nazarenos de Nuestro Señor de la Pasión Despojado de sus Vestiduras, María Santísima de la Amargura, Madre de la Iglesia y San Juan Evangelista', s: 'Parroquia de El Salvador', f: '1984', web: 'http://www.amarguradejaen.es',
  t: [['Nuestro Señor de la Pasión Despojado de sus Vestiduras', 'Miguel Zúñiga, 1989'], ['María Santísima de la Amargura, Madre de la Iglesia', 'anónima s. XVII (atribuida por expertos a José de Mora)']] });
add('los-estudiantes-jaen', 'estudiantes', { no: 'Ilustre y Franciscana Cofradía del Santísimo Cristo de las Misericordias y Nuestra Señora de las Lágrimas', s: 'Parroquia de Nuestra Señora de la Merced', f: '1946', web: 'http://estudiantes.comlu.com',
  t: [['Santísimo Cristo de las Misericordias («Cristo del Bambú»)', 'anónima'], ['Nuestra Señora de las Lágrimas', 'Juan Martínez Cerrillo, 1936-1938']],
  h: 'Su reunión fundacional se celebró el 16 de mayo de 1946 en San Bartolomé y quedó erigida canónicamente el 15 de diciembre de ese año. El Cristo de las Misericordias, conocido como Cristo del Bambú, pertenece a la comunidad clarisa y volvió a su monasterio en 1941 tras la guerra. La Virgen de las Lágrimas es de Juan Martínez Cerrillo, que la talló entre 1936 y 1938 para una hermandad cordobesa.' });
add('divino-maestro-lavatorio-jaen', 'divino-maestro', { no: 'Hermandad Misionera de Jesús Divino Maestro de Humildad y Entrega y María Santísima del Amor', s: 'Iglesia parroquial de Nuestra Señora de la Merced', f: '2015',
  t: [['Jesús Divino Maestro y apóstol San Pedro', 'Antonio José Martínez Rodríguez, 2015'], ['María Santísima del Amor', '']],
  h: 'Nació en el seno del colegio Divino Maestro de Jaén y está estrechamente ligada a la congregación de Misioneras del Divino Maestro, con quien comparte carisma. Jesús Divino Maestro y San Pedro son obra de Antonio Martínez Rodríguez (2015).' });
add('la-clemencia-jaen', 'clemencia', { no: 'Antigua, Ilustre y Real Cofradía del Santísimo Cristo de la Clemencia, Nuestro Padre Jesús de la Caída, Santa María Magdalena y María Santísima del Mayor Dolor', s: 'Iglesia de Santa María Magdalena', f: '1945',
  t: [['Santísimo Cristo de la Clemencia', 'Salvador de Cuéllar, 1593'], ['Nuestro Padre Jesús de la Caída', 'Emilio Navas-Parejo, 1956'], ['Santa María Magdalena', 'atrib. Mateo de Medina, s. XVIII'], ['María Santísima del Mayor Dolor', 'Alfredo Muñoz Arcos, 1946']] });
add('el-silencio-jaen', 'humildad-y-silencio', { no: 'Hermandad de Penitencia y Cofradía de Nazarenos de Silencio del Santísimo Cristo de la Humildad y María Santísima Madre de Dios', s: 'Iglesia parroquial de Cristo Rey', f: '1955', web: 'http://www.humildadysilencio.org',
  t: [['Santísimo Cristo de la Humildad', 'anónima s. XVI'], ['María Santísima Madre de Dios', '']],
  h: 'Fundada en 1955 con la idea de crear en Jaén una cofradía de silencio al estilo de las de otras ciudades; tuvo que esperar dos años para su primera estación de penitencia. Su Cristo de la Humildad es una talla anónima del siglo XVI y lo portan 32 costaleros.' });
add('el-cautivo-jaen', 'cautivo', { no: 'Hermandad Penitencial y Cofradía de Nuestro Divino Redentor Jesús Cautivo en el abandono de sus discípulos, María Santísima de la Trinidad y Santa Isabel de Portugal', s: 'Parroquia de Santa Isabel de Portugal', f: '2012 (grupo fundado en 2004)', web: 'http://www.cautivoytrinidadjaen.com',
  t: [['Nuestro Divino Redentor Jesús Cautivo', ''], ['María Santísima de la Trinidad', 'Francisco Romero Zafra, 2008']],
  h: 'El 18 de abril de 2004 un grupo de jóvenes cofrades fundó en la parroquia de la Santa Cruz el grupo «Santa Cruz», germen de esta hermandad de carisma trinitario, constituida en 2012. La Virgen de la Trinidad es del cordobés Francisco Romero Zafra (2008) y se bendijo el 6 de junio de 2009.' });
add('el-perdon-jaen', 'perdon', { no: 'Ilustre Hermandad del Santísimo Sacramento y Cofradía de Nazarenos de Jesús del Perdón, Cristo del Amor en su Prendimiento, María Santísima de la Esperanza, San Pedro y San Juan Apóstoles', s: 'Parroquia de Cristo Rey', f: '1952', web: 'http://www.cofradiadelperdon.com',
  t: [['Jesús del Perdón', 'Francisco Palma Burgos, 1955'], ['Cristo del Amor en su Prendimiento (misterio)', 'José Antonio Navarro Arteaga, 1992'], ['María Santísima de la Esperanza', '']],
  h: 'Se fundó el 8 de junio de 1952, salió por primera vez el Domingo de Ramos de 1954 y desde 1980 procesiona el Miércoles Santo. Jesús del Perdón es de Francisco Palma Burgos (1955) y el misterio del Prendimiento, del trianero José Antonio Navarro Arteaga.' });
add('la-buena-muerte-jaen', 'buena-muerte', { no: 'Real Hermandad Sacramental y Cofradía de Nazarenos del Santísimo Cristo de la Buena Muerte, Cristo Descendido de la Cruz y Nuestra Señora de las Angustias', s: 'Santa Iglesia Catedral de Jaén', f: '1926', web: 'http://www.buenamuertejaen.com',
  t: [['Santísimo Cristo de la Buena Muerte', 'Jacinto Higueras Fuentes, 1927'], ['Cristo Descendido de la Cruz', 'Víctor de los Ríos, 1959'], ['Nuestra Señora de las Angustias', 'atrib. José de Mora, principios s. XVIII']] });
add('la-lanzada-jaen', 'lanzada', { no: 'Hermandad Sacramental del Dulce Nombre de Jesús y Cofradía de Nazarenos del Santísimo Cristo de las Aguas en su Sagrada Lanzada, Purísima e Inmaculada Concepción de Nuestra Señora, María Santísima Reina de los Ángeles, San Juan Evangelista y San Francisco de Asís', s: 'Parroquia de La Inmaculada y San Pedro Pascual', f: '2023', web: 'https://sagradalanzadadejaen.wordpress.com',
  t: [['Santísimo Cristo de las Aguas', 'José Miguel Tirao Carpio, 2022'], ['María Santísima Reina de los Ángeles', 'José Miguel Tirao Carpio, 2016']] });
add('el-gran-poder-jaen', 'gran-poder', { no: 'Hermandad Penitencial del Triunfo de la Santa Cruz y Cofradía de Nazarenos de Jesús del Gran Poder en el encuentro con su Bendita Madre María Santísima del Dulce Nombre en la calle de la Amargura, Santa María Magdalena y San Juan Evangelista', s: 'Iglesia parroquial de la Santa Cruz' });
add('la-vera-cruz-los-civiles-jaen', 'vera-cruz', { no: 'Primitiva, Pontificia y Real Congregación del Santísimo Cristo de la Vera Cruz y María Santísima de los Dolores', s: 'Basílica Menor de San Ildefonso', f: '1541', web: 'http://www.veracruzjaen.es',
  t: [['Jesús Preso', 'Ramón Mateu Montesinos, 1943'], ['Santísimo Cristo de la Vera Cruz', 'Domingo Sánchez Mesa (réplica del Cristo de las Misericordias de José de Mora)'], ['María Santísima de los Dolores', 'Domingo Sánchez Mesa']],
  h: 'Fundada en mayo de 1541 en el antiguo convento de San Francisco, es la primera cofradía penitencial de Jaén. Participa en dos jornadas: el Domingo de Ramos con la Oración en el Huerto y la Virgen de los Desamparados, y el Jueves Santo con Jesús Preso, el Cristo de la Vera Cruz y la Virgen de los Dolores. Jesús Preso es de Ramón Mateu (1943) y procesiona en un paso de 1903 de Emilio Pizarro que perteneció al Baratillo de Sevilla.' });
add('la-expiracion-jaen', 'expiracion', { no: 'Real Hermandad Sacramental y Cofradía de Nazarenos del Santísimo Cristo de la Expiración, María Santísima de las Siete Palabras y San Juan Evangelista', s: 'Iglesia de San Bartolomé', f: '1761', web: 'http://www.expiracionjaen.net',
  t: [['Santísimo Cristo de la Expiración', 'atrib. José de Medina, 1761'], ['María Santísima de las Siete Palabras', 'Luis Álvarez Duarte, 1995'], ['San Juan Evangelista', 'José Martínez Puertas, 1943']] });
add('nuestro-padre-jesus-el-abuelo-jaen', 'ntro-padre-jesus', { no: 'Antigua, Insigne y Real Cofradía de Nuestro Padre Jesús Nazareno y Nuestra Señora de los Dolores', s: 'Iglesia de San José de los Descalzos y Santuario de Nuestro Padre Jesús', f: '1588', web: 'http://www.cofradiaelabuelo.com',
  t: [['Nuestro Padre Jesús Nazareno («El Abuelo»)', 'anónima s. XVI'], ['María Santísima de los Dolores', 'José de Medina, 1741'], ['Santa Marcela (Verónica)', 'Modesto y Damián Pastor y Julia, 1883'], ['Simón de Cirene', 'Luis Carlos Montesinos, 1892']] });
add('la-soledad-jaen', 'soledad', { no: 'Pontificia y Real Cofradía del Santísimo Cristo Yacente y Siervos de Nuestra Señora de la Soledad', s: 'Basílica Parroquial de San Ildefonso', f: '1556', web: 'http://www.soledadjaen.es',
  t: [['Santísimo Cristo Yacente', 'Constantino Unghetti, 1959'], ['Nuestra Señora de la Soledad', 'Antonio Bernal Redondo y Francisco Romero Zafra, 2000']] });
add('el-santo-sepulcro-jaen', 'sepulcro', { no: 'Antigua, Insigne, Venerable y Real Congregación del Santo Sepulcro de Cristo y Siervos de la Orden Tercera de Nuestra Señora de los Dolores', s: 'Iglesia parroquial de San Juan y San Pedro', f: '1580', web: 'https://santosepulcrojaen.wordpress.com',
  t: [['Santísimo Cristo del Calvario, San Juan, Dimas y Gestas', 'atrib. Sebastián de Solís, h. 1579'], ['Santa María del Silencio', 'atrib. José de Medina, mediados s. XVIII'], ['Cristo muerto en el Sepulcro', 'Juan Abascal Fuentes']] });
add('el-resucitado-jaen', 'resucitado', { no: 'Cofradía del Señor Resucitado y María Santísima de la Victoria', s: 'Basílica de San Ildefonso', f: '1987', web: 'http://www.resurreccionjaen.es',
  t: [['Jesús en el Misterio de su Gloriosa Resurrección', 'Rafael Rubio Vernia, 1951'], ['María Santísima de la Victoria', 'Alfredo Muñoz Arcos, 1955']] });

module.exports = E;
